import AppStore from "../AppStore";
import FNBStore from "../individualStore/banks/FNBStore";
import NEDBANKStore from "../individualStore/banks/NEDBANKStore";
import BankingTransactionStore from "../individualStore/banks/banking/BankingTransactionStore";
import CreditNoteStore from "../individualStore/credit-notes-returns/CreditNotesStore";
import SupplierReturnStore from "../individualStore/credit-notes-returns/SupplierReturns";
import CopiedInvoiceStore from "../individualStore/invoice/CopiedInvoiceStore";
import InvoiceStore from "../individualStore/invoice/InvoiceStore";
import RecuringInvoiceStore from "../individualStore/invoice/RecuringInvoice";
import SupplierInvoiceStore from "../individualStore/invoice/SupplierInvoiceStore";
import FinancialMonthStore from "../individualStore/months/FinancialMonth";
import BodyCopStore from "../individualStore/properties/BodyCopStore";
import UnitStore from "../individualStore/properties/UnitStore";
import PropertyBankAccountStore from "../individualStore/property-bank-account/PropertyBankAccountStore";
import ReceiptsPaymentStore from "../individualStore/receipts-payments/ReceiptsPaymentStore";
import CustomerTransactionsStore from "../individualStore/transactions/customer-transactions/CustomerTransactionsStore";
import SupplierTransactionsStore from "../individualStore/transactions/supplierTransactions/SupplierTransactionsStore";
import AccountCategoryStore from "../individualStore/type/AccountCategoryStore";
import AccountStore from "../individualStore/type/AccountStore";
import SupplierStore from "../individualStore/type/SupplierStore";
import TransferStore from "../individualStore/type/Transfer";
import FinancialYearStore from "../individualStore/years/FinancialYear";

export default class BodyCorporateStore {
  bodyCop: BodyCopStore;
  unit: UnitStore;
  financialYear: FinancialYearStore;
  financialMonth: FinancialMonthStore;
  invoice: InvoiceStore;
  recuringInvoice: RecuringInvoiceStore;
  copiedInvoices: CopiedInvoiceStore;
  fnb: FNBStore;
  nedbank: NEDBANKStore;
  supplier: SupplierStore;
  transfer: TransferStore;
  account: AccountStore;
  supplierInvoice: SupplierInvoiceStore;
  receiptsPayments: ReceiptsPaymentStore;
  creditNote: CreditNoteStore;
  propetyBankAccount: PropertyBankAccountStore;
  supplierReturn: SupplierReturnStore;
  accountCategory: AccountCategoryStore;
  bankingTransactions: BankingTransactionStore;
  customerTransactions: CustomerTransactionsStore;
  supplierTransactions: SupplierTransactionsStore;

  constructor(store: AppStore) {
    this.bodyCop = new BodyCopStore(store);
    this.unit = new UnitStore(store);
    this.financialYear = new FinancialYearStore(store);
    this.financialMonth = new FinancialMonthStore(store);
    this.invoice = new InvoiceStore(store);
    this.recuringInvoice = new RecuringInvoiceStore(store);
    this.copiedInvoices = new CopiedInvoiceStore(store);
    this.fnb = new FNBStore(store);
    this.nedbank = new NEDBANKStore(store);
    this.supplier = new SupplierStore(store);
    this.transfer = new TransferStore(store);
    this.account = new AccountStore(store);
    this.supplierInvoice = new SupplierInvoiceStore(store);
    this.receiptsPayments = new ReceiptsPaymentStore(store);
    this.creditNote = new CreditNoteStore(store);
    this.propetyBankAccount = new PropertyBankAccountStore(store);
    this.supplierReturn = new SupplierReturnStore(store);
    this.accountCategory = new AccountCategoryStore(store);
    this.bankingTransactions = new BankingTransactionStore(store);
    this.customerTransactions = new CustomerTransactionsStore(store);
    this.supplierTransactions = new SupplierTransactionsStore(store);
  }
}
